<?php

namespace AppBundle\Repository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginaArticulos($pagina=1,$numArticulos=3)
    {
        $query = $this->createQueryBuilder('a')
            ->setFirstResult($numArticulos*($pagina-1))
            ->setMaxResults(9999)
            ->orderBy('a.titulo', 'ASC')
            ->getQuery();
            return $query->getResult();
    }
}